import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
const candidate = 'e2bdaee3a1f8644451b23dd9d41c1234a1b381e6';
const gitBlob = data => createHash('sha1').update(`blob ${Buffer.byteLength(data)}\0`).update(data).digest('hex');
const view = await fs.readFile('../../../../core/resources/views/landlord/frontend/onboarding/store-setup.blade.php');
if (gitBlob(view) !== 'c1a3273e8bf4d51cfe3b1f2b217b99a7103cad30') throw new Error('Unexpected application view source');
await import('./engineer-e2e.mjs');
const frozen = await fs.readFile('./salem-ui-review.historical.mjs', 'utf8');
if (gitBlob(frozen) !== 'b09f0fa87fe1b36b45706c23c9267f54be1444eb') throw new Error('Historical QA assertions changed');
const patched = frozen.replace("application_candidate: 'ef2cee35d42d6834d3ca8acda019d79628faf68b'", `application_candidate: '${candidate}'`);
if (patched === frozen) throw new Error('Expected candidate metadata not found');
await fs.writeFile('./salem-ui-review.current.mjs', patched);
await fs.writeFile(`${process.env.G01_EVIDENCE_DIR}/salem-test-provenance.json`, JSON.stringify({ application_candidate: candidate, view_blob: gitBlob(view), historical_test_blob: gitBlob(frozen), historical_edit: 'Only application_candidate metadata changed. All 12 checks and assertions unchanged.', engineer_script_blob: gitBlob(await fs.readFile('./engineer-e2e.mjs')) }, null, 2));
await import('./salem-ui-review.current.mjs');
await import('./salem-acceptance.mjs');
