<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Backfill default theme colors for existing tenants.
 * Uses INSERT IGNORE so tenants who already customized their colors are unaffected.
 */
return new class extends Migration
{
    private array $defaults = [
        // ── BakerCo ────────────────────────────────────────────────────────
        'main_color_one_bakerco'       => '#D4856A',
        'main_color_two_bakerco'       => '#B5694E',
        'main_color_three_bakerco'     => '#C49A6C',
        'secondary_color_bakerco'      => '#F9EDE8',
        'secondary_color_two_bakerco'  => '#F5EAD8',
        'section_bg_1_bakerco'         => '#FDF5E6',
        'section_bg_2_bakerco'         => '#FAF0DC',
        'section_bg_3_bakerco'         => '#F9EDE8',
        'section_bg_4_bakerco'         => '#F5EAD8',
        'section_bg_5_bakerco'         => '#FDF5E6',
        'section_bg_6_bakerco'         => '#E8D5C4',
        'breadcrumb_bg_bakerco'        => '#FDF5E6',
        'heading_color_bakerco'        => '#3D1C12',
        'body_color_bakerco'           => '#7A5A4A',
        'light_color_bakerco'          => '#7A5A4A',
        'extra_light_color_bakerco'    => '#E8D5C4',
        'review_color_bakerco'         => '#FABE50',
        'feedback_bg_item_bakerco'     => '#F9EDE8',
        'new_color_bakerco'            => '#5AB27E',
        'body_font_family_bakerco'     => 'Lato',
        'heading_font_family_bakerco'  => 'Playfair Display',
        // ── ChefHome ───────────────────────────────────────────────────────
        'main_color_one_chefhome'      => '#C0392B',
        'main_color_two_chefhome'      => '#96281B',
        'main_color_three_chefhome'    => '#E67E22',
        'secondary_color_chefhome'     => '#FFF0EC',
        'secondary_color_two_chefhome' => '#FAF0E6',
        'section_bg_1_chefhome'        => '#FDF8F3',
        'section_bg_2_chefhome'        => '#FAF0E6',
        'section_bg_3_chefhome'        => '#FFF0EC',
        'section_bg_4_chefhome'        => '#EAD9CF',
        'section_bg_5_chefhome'        => '#FDF8F3',
        'section_bg_6_chefhome'        => '#EAD9CF',
        'breadcrumb_bg_chefhome'       => '#FDF8F3',
        'heading_color_chefhome'       => '#1A0A00',
        'body_color_chefhome'          => '#7D6057',
        'light_color_chefhome'         => '#7D6057',
        'extra_light_color_chefhome'   => '#EAD9CF',
        'review_color_chefhome'        => '#FABE50',
        'feedback_bg_item_chefhome'    => '#FFF0EC',
        'new_color_chefhome'           => '#27AE60',
        // ── DriveKit ───────────────────────────────────────────────────────
        'main_color_one_drivekit'      => '#E53030',
        'main_color_two_drivekit'      => '#B71C1C',
        'main_color_three_drivekit'    => '#FF6D00',
        'secondary_color_drivekit'     => '#1A1C1F',
        'secondary_color_two_drivekit' => '#222528',
        'section_bg_1_drivekit'        => '#111214',
        'section_bg_2_drivekit'        => '#17191C',
        'section_bg_3_drivekit'        => '#1A1C1F',
        'section_bg_4_drivekit'        => '#222528',
        'section_bg_5_drivekit'        => '#0A0A0A',
        'section_bg_6_drivekit'        => '#2E3135',
        'breadcrumb_bg_drivekit'       => '#111214',
        'heading_color_drivekit'       => '#F0F2F5',
        'body_color_drivekit'          => '#9BA3AE',
        'light_color_drivekit'         => '#9BA3AE',
        'extra_light_color_drivekit'   => '#2E3135',
        'review_color_drivekit'        => '#FABE50',
        'feedback_bg_item_drivekit'    => '#1A1C1F',
        'new_color_drivekit'           => '#5AB27E',
        // ── FitPeak ────────────────────────────────────────────────────────
        'main_color_one_fitpeak'       => '#00FF41',
        'main_color_two_fitpeak'       => '#00CC33',
        'main_color_three_fitpeak'     => '#007A1F',
        'secondary_color_fitpeak'      => '#161616',
        'secondary_color_two_fitpeak'  => '#1E1E1E',
        'section_bg_1_fitpeak'         => '#0A0A0A',
        'section_bg_2_fitpeak'         => '#111111',
        'section_bg_3_fitpeak'         => '#161616',
        'section_bg_4_fitpeak'         => '#1E1E1E',
        'section_bg_5_fitpeak'         => '#0A0A0A',
        'section_bg_6_fitpeak'         => '#1A3A1A',
        'breadcrumb_bg_fitpeak'        => '#111111',
        'heading_color_fitpeak'        => '#E0E0E0',
        'body_color_fitpeak'           => '#707070',
        'light_color_fitpeak'          => '#707070',
        'extra_light_color_fitpeak'    => '#1A3A1A',
        'review_color_fitpeak'         => '#FABE50',
        'feedback_bg_item_fitpeak'     => '#161616',
        'new_color_fitpeak'            => '#00FF41',
        // ── FreshMart ──────────────────────────────────────────────────────
        'main_color_one_freshmart'     => '#2E7D32',
        'main_color_two_freshmart'     => '#1B5E20',
        'main_color_three_freshmart'   => '#4CAF50',
        'secondary_color_freshmart'    => '#E8F5E9',
        'secondary_color_two_freshmart'=> '#FFF3E0',
        'section_bg_1_freshmart'       => '#F8FDF8',
        'section_bg_2_freshmart'       => '#E8F5E9',
        'section_bg_3_freshmart'       => '#FFF3E0',
        'section_bg_4_freshmart'       => '#F8FDF8',
        'section_bg_5_freshmart'       => '#E8F5E9',
        'section_bg_6_freshmart'       => '#C8E6C9',
        'breadcrumb_bg_freshmart'      => '#F8FDF8',
        'heading_color_freshmart'      => '#1B2E1B',
        'body_color_freshmart'         => '#5A6E5A',
        'light_color_freshmart'        => '#5A6E5A',
        'extra_light_color_freshmart'  => '#C8E6C9',
        'review_color_freshmart'       => '#FABE50',
        'feedback_bg_item_freshmart'   => '#E8F5E9',
        'new_color_freshmart'          => '#FF6F00',
        // ── GlowLab ────────────────────────────────────────────────────────
        'main_color_one_glowlab'       => '#B8965A',
        'main_color_two_glowlab'       => '#D4AF6A',
        'main_color_three_glowlab'     => '#8FAF8A',
        'secondary_color_glowlab'      => '#FBF6EE',
        'secondary_color_two_glowlab'  => '#F5EBE0',
        'section_bg_1_glowlab'         => '#FAFAFA',
        'section_bg_2_glowlab'         => '#FBF6EE',
        'section_bg_3_glowlab'         => '#F5EBE0',
        'section_bg_4_glowlab'         => '#EDE4D8',
        'section_bg_5_glowlab'         => '#FAFAFA',
        'section_bg_6_glowlab'         => '#EDE4D8',
        'breadcrumb_bg_glowlab'        => '#FBF6EE',
        'heading_color_glowlab'        => '#1C1410',
        'body_color_glowlab'           => '#7A6A5A',
        'light_color_glowlab'          => '#7A6A5A',
        'extra_light_color_glowlab'    => '#EDE4D8',
        'review_color_glowlab'         => '#FABE50',
        'feedback_bg_item_glowlab'     => '#FBF6EE',
        'new_color_glowlab'            => '#8FAF8A',
        // ── GoldCraft ──────────────────────────────────────────────────────
        'main_color_one_goldcraft'     => '#C9806A',
        'main_color_two_goldcraft'     => '#A86552',
        'main_color_three_goldcraft'   => '#C8A96E',
        'secondary_color_goldcraft'    => '#F5EAE0',
        'secondary_color_two_goldcraft'=> '#EDE0C8',
        'section_bg_1_goldcraft'       => '#FAF7F2',
        'section_bg_2_goldcraft'       => '#F9F5EE',
        'section_bg_3_goldcraft'       => '#F0E8D8',
        'section_bg_4_goldcraft'       => '#EDE0C8',
        'section_bg_5_goldcraft'       => '#FAF7F2',
        'section_bg_6_goldcraft'       => '#DDD0BC',
        'breadcrumb_bg_goldcraft'      => '#FAF7F2',
        'heading_color_goldcraft'      => '#2A1F14',
        'body_color_goldcraft'         => '#8A7468',
        'light_color_goldcraft'        => '#8A7468',
        'extra_light_color_goldcraft'  => '#DDD0BC',
        'review_color_goldcraft'       => '#FABE50',
        'feedback_bg_item_goldcraft'   => '#F9F5EE',
        'new_color_goldcraft'          => '#5AB27E',
        // ── KidVille ───────────────────────────────────────────────────────
        'main_color_one_kidville'      => '#E53935',
        'main_color_two_kidville'      => '#1565C0',
        'main_color_three_kidville'    => '#43A047',
        'secondary_color_kidville'     => '#FFEBEE',
        'secondary_color_two_kidville' => '#E3F2FD',
        'section_bg_1_kidville'        => '#FFFEF8',
        'section_bg_2_kidville'        => '#FFEBEE',
        'section_bg_3_kidville'        => '#E3F2FD',
        'section_bg_4_kidville'        => '#E8F5E9',
        'section_bg_5_kidville'        => '#FFFDE7',
        'section_bg_6_kidville'        => '#E0E0E0',
        'breadcrumb_bg_kidville'       => '#FFFEF8',
        'heading_color_kidville'       => '#1A1A2E',
        'body_color_kidville'          => '#5A5A6E',
        'light_color_kidville'         => '#5A5A6E',
        'extra_light_color_kidville'   => '#E0E0E0',
        'review_color_kidville'        => '#FDD835',
        'feedback_bg_item_kidville'    => '#FFEBEE',
        'new_color_kidville'           => '#43A047',
        // ── LuxeGems ───────────────────────────────────────────────────────
        'main_color_one_luxegems'      => '#C9A84C',
        'main_color_two_luxegems'      => '#A88530',
        'main_color_three_luxegems'    => '#F0D98C',
        'secondary_color_luxegems'     => '#141414',
        'secondary_color_two_luxegems' => '#1A1400',
        'section_bg_1_luxegems'        => '#080808',
        'section_bg_2_luxegems'        => '#111111',
        'section_bg_3_luxegems'        => '#141414',
        'section_bg_4_luxegems'        => '#1A1400',
        'section_bg_5_luxegems'        => '#080808',
        'section_bg_6_luxegems'        => '#2A2410',
        'breadcrumb_bg_luxegems'       => '#111111',
        'heading_color_luxegems'       => '#E8E0D0',
        'body_color_luxegems'          => '#8A7E6E',
        'light_color_luxegems'         => '#8A7E6E',
        'extra_light_color_luxegems'   => '#2A2410',
        'review_color_luxegems'        => '#C9A84C',
        'feedback_bg_item_luxegems'    => '#141414',
        'new_color_luxegems'           => '#C9A84C',
        // ── Maison ─────────────────────────────────────────────────────────
        'main_color_one_maison'        => '#C8B89A',
        'main_color_two_maison'        => '#A8967A',
        'main_color_three_maison'      => '#7D8C5A',
        'secondary_color_maison'       => '#EDDFCE',
        'secondary_color_two_maison'   => '#F3EDE0',
        'section_bg_1_maison'          => '#FAF7F2',
        'section_bg_2_maison'          => '#F3EDE0',
        'section_bg_3_maison'          => '#EDDFCE',
        'section_bg_4_maison'          => '#DDD5C4',
        'section_bg_5_maison'          => '#FAF7F2',
        'section_bg_6_maison'          => '#DDD5C4',
        'breadcrumb_bg_maison'         => '#FAF7F2',
        'heading_color_maison'         => '#1E1A14',
        'body_color_maison'            => '#8A8070',
        'light_color_maison'           => '#8A8070',
        'extra_light_color_maison'     => '#DDD5C4',
        'review_color_maison'          => '#FABE50',
        'feedback_bg_item_maison'      => '#F3EDE0',
        'new_color_maison'             => '#7D8C5A',
        // ── PawHaus ────────────────────────────────────────────────────────
        'main_color_one_pawhaus'       => '#C87040',
        'main_color_two_pawhaus'       => '#A05A30',
        'main_color_three_pawhaus'     => '#7D9B76',
        'secondary_color_pawhaus'      => '#FDF0E6',
        'secondary_color_two_pawhaus'  => '#EBF3EA',
        'section_bg_1_pawhaus'         => '#FAFAF7',
        'section_bg_2_pawhaus'         => '#FBF6EF',
        'section_bg_3_pawhaus'         => '#FDF0E6',
        'section_bg_4_pawhaus'         => '#EBF3EA',
        'section_bg_5_pawhaus'         => '#FAFAF7',
        'section_bg_6_pawhaus'         => '#E8DED2',
        'breadcrumb_bg_pawhaus'        => '#FBF6EF',
        'heading_color_pawhaus'        => '#2D2318',
        'body_color_pawhaus'           => '#7A6A5A',
        'light_color_pawhaus'          => '#7A6A5A',
        'extra_light_color_pawhaus'    => '#E8DED2',
        'review_color_pawhaus'         => '#FABE50',
        'feedback_bg_item_pawhaus'     => '#FDF0E6',
        'new_color_pawhaus'            => '#7D9B76',
        // ── Pharmacy ───────────────────────────────────────────────────────
        'main_color_one_pharmacy'      => '#00C896',
        'main_color_two_pharmacy'      => '#009E78',
        'main_color_three_pharmacy'    => '#1565C0',
        'secondary_color_pharmacy'     => '#E0FBF4',
        'secondary_color_two_pharmacy' => '#EBF1FF',
        'section_bg_1_pharmacy'        => '#F4F7FF',
        'section_bg_2_pharmacy'        => '#E0FBF4',
        'section_bg_3_pharmacy'        => '#EBF1FF',
        'section_bg_4_pharmacy'        => '#F4F7FF',
        'section_bg_5_pharmacy'        => '#FFFFFF',
        'section_bg_6_pharmacy'        => '#DDE4EF',
        'breadcrumb_bg_pharmacy'       => '#F4F7FF',
        'heading_color_pharmacy'       => '#0A1628',
        'body_color_pharmacy'          => '#5A6A85',
        'light_color_pharmacy'         => '#5A6A85',
        'extra_light_color_pharmacy'   => '#DDE4EF',
        'review_color_pharmacy'        => '#FABE50',
        'feedback_bg_item_pharmacy'    => '#E0FBF4',
        'new_color_pharmacy'           => '#00C896',
        // ── SportZone ──────────────────────────────────────────────────────
        'main_color_one_sportzone'     => '#C62828',
        'main_color_two_sportzone'     => '#8E0000',
        'main_color_three_sportzone'   => '#0D1B3E',
        'secondary_color_sportzone'    => '#FFEBEE',
        'secondary_color_two_sportzone'=> '#F5F5F5',
        'section_bg_1_sportzone'       => '#F5F5F5',
        'section_bg_2_sportzone'       => '#FFEBEE',
        'section_bg_3_sportzone'       => '#FFFFFF',
        'section_bg_4_sportzone'       => '#F5F5F5',
        'section_bg_5_sportzone'       => '#FFEBEE',
        'section_bg_6_sportzone'       => '#DDDDDD',
        'breadcrumb_bg_sportzone'      => '#F5F5F5',
        'heading_color_sportzone'      => '#111111',
        'body_color_sportzone'         => '#555555',
        'light_color_sportzone'        => '#555555',
        'extra_light_color_sportzone'  => '#DDDDDD',
        'review_color_sportzone'       => '#FABE50',
        'feedback_bg_item_sportzone'   => '#FFEBEE',
        'new_color_sportzone'          => '#5AB27E',
        // ── TechZone ───────────────────────────────────────────────────────
        'main_color_one_techzone'      => '#0066FF',
        'main_color_two_techzone'      => '#0047B3',
        'main_color_three_techzone'    => '#00C853',
        'secondary_color_techzone'     => '#1C2128',
        'secondary_color_two_techzone' => '#21262D',
        'section_bg_1_techzone'        => '#0D1117',
        'section_bg_2_techzone'        => '#161B22',
        'section_bg_3_techzone'        => '#1C2128',
        'section_bg_4_techzone'        => '#21262D',
        'section_bg_5_techzone'        => '#0D1117',
        'section_bg_6_techzone'        => '#30363D',
        'breadcrumb_bg_techzone'       => '#161B22',
        'heading_color_techzone'       => '#CDD9E5',
        'body_color_techzone'          => '#636E7B',
        'light_color_techzone'         => '#636E7B',
        'extra_light_color_techzone'   => '#30363D',
        'review_color_techzone'        => '#FABE50',
        'feedback_bg_item_techzone'    => '#1C2128',
        'new_color_techzone'           => '#00C853',
        // ── TinyNest ───────────────────────────────────────────────────────
        'main_color_one_tinynest'      => '#B39DDB',
        'main_color_two_tinynest'      => '#7E57C2',
        'main_color_three_tinynest'    => '#26A69A',
        'secondary_color_tinynest'     => '#EDE8F5',
        'secondary_color_two_tinynest' => '#FDFAF8',
        'section_bg_1_tinynest'        => '#FDFAF8',
        'section_bg_2_tinynest'        => '#EDE8F5',
        'section_bg_3_tinynest'        => '#FFCCBC',
        'section_bg_4_tinynest'        => '#B3E5FC',
        'section_bg_5_tinynest'        => '#FFF9C4',
        'section_bg_6_tinynest'        => '#EDE8F5',
        'breadcrumb_bg_tinynest'       => '#FDFAF8',
        'heading_color_tinynest'       => '#2E2438',
        'body_color_tinynest'          => '#8A7F9A',
        'light_color_tinynest'         => '#8A7F9A',
        'extra_light_color_tinynest'   => '#EDE8F5',
        'review_color_tinynest'        => '#FABE50',
        'feedback_bg_item_tinynest'    => '#EDE8F5',
        'new_color_tinynest'           => '#26A69A',
        // ── TrailCo ────────────────────────────────────────────────────────
        'main_color_one_trailco'       => '#4A5E3A',
        'main_color_two_trailco'       => '#2E3D22',
        'main_color_three_trailco'     => '#C47C5A',
        'secondary_color_trailco'      => '#EAF0E3',
        'secondary_color_two_trailco'  => '#F7EDE6',
        'section_bg_1_trailco'         => '#F4F1EC',
        'section_bg_2_trailco'         => '#EAF0E3',
        'section_bg_3_trailco'         => '#F7EDE6',
        'section_bg_4_trailco'         => '#F4F1EC',
        'section_bg_5_trailco'         => '#EAF0E3',
        'section_bg_6_trailco'         => '#D6CFC4',
        'breadcrumb_bg_trailco'        => '#F4F1EC',
        'heading_color_trailco'        => '#1E2019',
        'body_color_trailco'           => '#6B6456',
        'light_color_trailco'          => '#6B6456',
        'extra_light_color_trailco'    => '#D6CFC4',
        'review_color_trailco'         => '#FABE50',
        'feedback_bg_item_trailco'     => '#EAF0E3',
        'new_color_trailco'            => '#C47C5A',
        // ── VelvetLux ──────────────────────────────────────────────────────
        'main_color_one_velvetlux'     => '#5C1F6B',
        'main_color_two_velvetlux'     => '#3D1248',
        'main_color_three_velvetlux'   => '#C4A45E',
        'secondary_color_velvetlux'    => '#F0E8F4',
        'secondary_color_two_velvetlux'=> '#F5EDD0',
        'section_bg_1_velvetlux'       => '#F8F5F2',
        'section_bg_2_velvetlux'       => '#F0E8F4',
        'section_bg_3_velvetlux'       => '#F5EDD0',
        'section_bg_4_velvetlux'       => '#F8F5F2',
        'section_bg_5_velvetlux'       => '#F0E8F4',
        'section_bg_6_velvetlux'       => '#E0D4E8',
        'breadcrumb_bg_velvetlux'      => '#F8F5F2',
        'heading_color_velvetlux'      => '#1A0820',
        'body_color_velvetlux'         => '#7A6882',
        'light_color_velvetlux'        => '#7A6882',
        'extra_light_color_velvetlux'  => '#E0D4E8',
        'review_color_velvetlux'       => '#FABE50',
        'feedback_bg_item_velvetlux'   => '#F0E8F4',
        'new_color_velvetlux'          => '#C4A45E',
    ];

    public function up(): void
    {
        $now = now()->toDateTimeString();
        $rows = [];
        foreach ($this->defaults as $key => $value) {
            $rows[] = "('{$key}', '{$value}', '{$now}', '{$now}')";
        }

        // INSERT IGNORE: skips any key the tenant already has (e.g. admin-customised colours).
        DB::statement(
            'INSERT IGNORE INTO `static_options` (`option_name`, `option_value`, `created_at`, `updated_at`) VALUES '
            . implode(',', $rows)
        );
    }

    public function down(): void
    {
        $keys = array_map(fn($k) => "'{$k}'", array_keys($this->defaults));
        DB::statement('DELETE FROM `static_options` WHERE `option_name` IN (' . implode(',', $keys) . ')');
    }
};
